In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("TopSellingAlbums.csv")

In [3]:
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0

In [4]:
df.tail()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN,7.5
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y,7.0
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN,6.5

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Artist                            8 non-null      object
 1   Album                             8 non-null      object
 2   Released                          8 non-null      int64
 3   Length                            8 non-null      object
 4   Genre                             8 non-null      object
 5   Music Recording Sales (millions)  8 non-null      float64
 6   Claimed Sales (millions)          8 non-null      int64
 7   Released.1                        8 non-null      object
 8   Soundtrack                        2 non-null      object
 9   Rating                            8 non-null      float64
dtypes: float64(2), int64(2), object(6)
memory usage: 768.0+ bytes

In [6]:
df.shape

(8, 10)

In [7]:
df.columns

Index(['Artist', 'Album', 'Released', 'Length', 'Genre',
       'Music Recording Sales (millions)', 'Claimed Sales (millions)',
       'Released.1', 'Soundtrack', 'Rating'],
      dtype='object')

In [8]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [9]:
df.describe()

,Released,Music Recording Sales (millions),Claimed Sales (millions),Rating
count,8.000000,8.000000,8.000000,8.000000
mean,1979.250000,28.125000,46.125000,8.250000
std,5.800246,8.189322,8.271077,1.224745
min,1973.000000,20.600000,40.000000,6.500000
25%,1976.750000,23.300000,41.500000,7.375000
50%,1977.000000,26.750000,43.500000,8.250000
75%,1980.500000,28.975000,46.250000,9.125000
max,1992.000000,46.000000,65.000000,10.000000