#### Carnegie Mellon University - Tepper School of Business
#### 46-881 - Programming in R and Python
#### 22/23 - Mini 2 - Sections MO2 - Farahat
---

## Deliverable 4 
**Due December 7th at 02:59 a.m.**

Please provide your name and Andrew ID below:

- Name (Last, First):Hrishikesh Mysore Harishkumar

- Andrew ID: hmysoreh

---

This deliverable consists of a single problem comprised of several parts. Each part requires you to write code in Python and/or provide a short written annswer. Save a copy of this notebook and provide your solution by inserting code or Markdown text files as appropriate.

The accompanying dataset simplified_airline_data.csv is available on Canvas.

You will need to submit two files through Canvas: 1) a completed Jupyter notebook (extension .ipynb) with your code and answers to each question (this file); and 2) an html rendering of your completed Jupyter notebook.

### Problem 1 (100 points)

#### Part(a)
Load the pandas and numpy packages.

In [1]:
import numpy as np
import pandas as pd

#### Part (b)
Read the data contained in the file simplified_airline_data.csv into a pandas DataFrame named df.

In [2]:
df = pd.read_csv("simplified_airline_data.csv")

#### Part (c)
Use the index and column attributes to print the row and column labels of df.

In [3]:
print(df.columns)

Index(['Flight number', 'Airline', 'Origin airport', 'Destination airport',
       'Date', 'Scheduled departure time', 'Scheduled arrival time',
       'Actual arrival time', 'Arrival delay minutes', 'Week day',
       'Route code'],
      dtype='object')

In [4]:
print(df.index)

RangeIndex(start=0, stop=372, step=1)

#### Part (d)
Can the Flight number column be used as an index to df? Explain.

### Answer:

#### The Flight Number cannot be used as an index to df as it will not create an array of unique values.

#### Part (e)
Print the last 5 rows of df

In [5]:
print(df.tail(5))

    Flight number Airline Origin airport Destination airport       Date  \
367        QU5520  Quanta            PIT                 LGA  8/27/2018
368        QU5520  Quanta            PIT                 LGA  8/28/2018
369        QU5520  Quanta            PIT                 LGA  8/29/2018
370        QU5520  Quanta            PIT                 LGA  8/30/2018
371        QU5520  Quanta            PIT                 LGA  8/31/2018

    Scheduled departure time Scheduled arrival time Actual arrival time  \
367                    13:35                  15:00               14:59
368                    13:35                  15:00               15:17
369                    13:35                  15:00               15:34
370                    13:35                  15:00               15:24
371                    13:35                  15:00               15:15

     Arrival delay minutes Week day Route code
367                   -1.0      Mon    PIT_LGA
368                   17.0      Tue    PIT_LGA
369                   34.0      Wed    PIT_LGA
370                   24.0      Thu    PIT_LGA
371                   15.0      Fri    PIT_LGA

In [6]:
df.tail(5)

,Flight number,Airline,Origin airport,Destination airport,Date,Scheduled departure time,Scheduled arrival time,Actual arrival time,Arrival delay minutes,Week day,Route code
367,QU5520,Quanta,PIT,LGA,8/27/2018,13:35,15:00,14:59,-1.0,Mon,PIT_LGA
368,QU5520,Quanta,PIT,LGA,8/28/2018,13:35,15:00,15:17,17.0,Tue,PIT_LGA
369,QU5520,Quanta,PIT,LGA,8/29/2018,13:35,15:00,15:34,34.0,Wed,PIT_LGA
370,QU5520,Quanta,PIT,LGA,8/30/2018,13:35,15:00,15:24,24.0,Thu,PIT_LGA
371,QU5520,Quanta,PIT,LGA,8/31/2018,13:35,15:00,15:15,15.0,Fri,PIT_LGA

#### Part (f)
Print rows 200-205 (inclusive) of df

In [7]:
df.iloc[[199,200,201,202,203,204], : ]

,Flight number,Airline,Origin airport,Destination airport,Date,Scheduled departure time,Scheduled arrival time,Actual arrival time,Arrival delay minutes,Week day,Route code
199,OP6832,Optima,PIT,LGA,8/15/2018,20:45,22:00,22:28,28.0,Wed,PIT_LGA
200,OP6812,Optima,PIT,LGA,8/16/2018,7:45,9:00,9:21,21.0,Thu,PIT_LGA
201,OP6822,Optima,PIT,LGA,8/16/2018,14:45,16:00,16:07,7.0,Thu,PIT_LGA
202,OP6832,Optima,PIT,LGA,8/16/2018,20:45,22:00,22:22,22.0,Thu,PIT_LGA
203,OP6812,Optima,PIT,LGA,8/17/2018,7:45,9:00,9:20,20.0,Fri,PIT_LGA
204,OP6822,Optima,PIT,LGA,8/17/2018,14:45,16:00,16:24,24.0,Fri,PIT_LGA

#### Part (g)
Sort df in *decreasing* order of "Arrival delay minutes" and print the 5 most delayed flights.

In [8]:
df_desc = df.sort_values(by=["Arrival delay minutes"], ascending=False)

In [9]:
df_desc.head(5)

,Flight number,Airline,Origin airport,Destination airport,Date,Scheduled departure time,Scheduled arrival time,Actual arrival time,Arrival delay minutes,Week day,Route code
351,QU5520,Quanta,PIT,LGA,8/11/2018,13:35,15:00,15:47,47.0,Sat,PIT_LGA
245,OP6812,Optima,PIT,LGA,8/31/2018,7:45,9:00,9:39,39.0,Fri,PIT_LGA
45,OP7644,Optima,LGA,PIT,8/5/2018,18:10,19:25,20:03,38.0,Sun,LGA_PIT
298,QU4422,Quanta,LGA,PIT,8/20/2018,21:55,23:20,23:55,35.0,Mon,LGA_PIT
208,OP6832,Optima,PIT,LGA,8/18/2018,20:45,22:00,22:34,34.0,Sat,PIT_LGA

#### Part (h)
Create a new column in df called "Delay indicator". Set this column to equal 1 if "Arrival delay minutes" equals or exceeds 15 minutes, and zero otherwise. If a flight has NaN in the "Arrival delay minutes" column then "Delay indicator" should display NaN as well. (Note: The FAA defines a flight as "delayed" if it arrives at its destination 15 or more minutes past its scheduled arrival time).

In [10]:
# create a list of conditions
conditions = [
    (df['Arrival delay minutes'] < 15),
    (df['Arrival delay minutes'] >= 15),
    (pd.isnull(df['Arrival delay minutes']))
    ]

In [11]:
# create a list of the values
values = [0, 1, "NaN"]

In [12]:
# create a new column -  Delay indicator and assign values to it

df['Delay indicator'] = np.select(conditions, values)

In [13]:
df

,Flight number,Airline,Origin airport,Destination airport,Date,Scheduled departure time,Scheduled arrival time,Actual arrival time,Arrival delay minutes,Week day,Route code,Delay indicator
0,OP3425,Optima,DCA,PIT,8/1/2018,18:05,19:35,19:51,16.0,Wed,DCA_PIT,1
1,OP3425,Optima,DCA,PIT,8/2/2018,18:05,19:35,19:50,15.0,Thu,DCA_PIT,1
2,OP3425,Optima,DCA,PIT,8/3/2018,18:05,19:35,19:39,4.0,Fri,DCA_PIT,0
3,OP3425,Optima,DCA,PIT,8/4/2018,18:05,19:35,19:49,14.0,Sat,DCA_PIT,0
4,OP3425,Optima,DCA,PIT,8/5/2018,18:05,19:35,19:37,2.0,Sun,DCA_PIT,0
...,...,...,...,...,...,...,...,...,...,...,...,...
367,QU5520,Quanta,PIT,LGA,8/27/2018,13:35,15:00,14:59,-1.0,Mon,PIT_LGA,0
368,QU5520,Quanta,PIT,LGA,8/28/2018,13:35,15:00,15:17,17.0,Tue,PIT_LGA,1
369,QU5520,Quanta,PIT,LGA,8/29/2018,13:35,15:00,15:34,34.0,Wed,PIT_LGA,1
370,QU5520,Quanta,PIT,LGA,8/30/2018,13:35,15:00,15:24,24.0,Thu,PIT_LGA,1
371,QU5520,Quanta,PIT,LGA,8/31/2018,13:35,15:00,15:15,15.0,Fri,PIT_LGA,1

#### Part (i)
What is the percentage of delayed flights (as indicated by the "Delay indicator" column) for Optima Airlines?

In [14]:
df_Optima = df[df["Airline"] == "Optima"]

In [15]:
total_O = len(df_Optima) - len(df_Optima[df_Optima['Delay indicator']== 'NaN']) 
delayed_O = len(df_Optima[df_Optima['Delay indicator']== '1'])
print(total_O)
print(delayed_O)

perc_delayed_Opt_flights = delayed_O / total_O

print(perc_delayed_Opt_flights * 100, '%')

248
111
44.75806451612903 %

#### Part (j)
What is the percentage of delayed flights (as indicated by the "Delay indicator" column) for Quanta Airlines?

In [16]:
df_Quanta = df[df["Airline"] == "Quanta"]

In [17]:
total_Q = len(df_Quanta) - len(df_Quanta[df_Quanta['Delay indicator']== 'NaN']) 
delayed_Q = len(df_Quanta[df_Quanta['Delay indicator']== '1'])
print(total_Q)
print(delayed_Q)

perc_delayed_Quanta_flights = delayed_Q / total_Q

print(perc_delayed_Quanta_flights * 100, '%')

112
50
44.642857142857146 %

#### Part (k)
Which airline do you think has the better on-time performance? Explain.

### Answer:

#### Looking at the percentage of delayed flights above, I think the on-time performance for both the airines is the same.

----

## END