In [4]:
import pandas as pd
import numpy as np

In [5]:
df_movies = pd.read_csv("movies.csv")

In [11]:
type(df_movies)

pandas.core.frame.DataFrame

In [12]:
df_movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [7]:
df_ratings = pd.read_csv("ratings.csv")

In [10]:
type(df_ratings)

pandas.core.frame.DataFrame

In [13]:
df_ratings

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [19]:
df_combined = pd.merge(df_movies, df_ratings, on='movieId').sort_values(by=['movieId'])

In [20]:
df_combined

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
137,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,382,4.5,1515162628
138,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,385,4.0,834691642
139,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,389,5.0,857934174
140,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,391,3.0,1032388077
...,...,...,...,...,...,...
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,1537109082
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,1537109545
100833,193585,Flint (2017),Drama,184,3.5,1537109805
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,1537110021
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,1537157606

In [21]:
df_combined.tail(5)

,movieId,title,genres,userId,rating,timestamp
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,1537109082
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,1537109545
100833,193585,Flint (2017),Drama,184,3.5,1537109805
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,1537110021
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,1537157606

In [33]:
mean_ratings = df_combined.pivot_table(index = 'title', aggfunc ='mean',values = 'rating').sort_values(by='rating')

In [34]:
mean_ratings.head(5)

                                            rating
title
Rust and Bone (De rouille et d'os) (2012)      0.5
The Emoji Movie (2017)                         0.5
The Butterfly Effect 3: Revelations (2009)     0.5
Follow Me, Boys! (1966)                        0.5
The Beast of Hollow Mountain (1956)            0.5

In [36]:
ratings_by_title = df_combined.groupby("title").size()

In [37]:
ratings_by_title

title
'71 (2014)                                    1
'Hellboy': The Seeds of Creation (2004)       1
'Round Midnight (1986)                        2
'Salem's Lot (2004)                           1
'Til There Was You (1997)                     2
                                             ..
eXistenZ (1999)                              22
xXx (2002)                                   24
xXx: State of the Union (2005)                5
¡Three Amigos! (1986)                        26
À nous la liberté (Freedom for Us) (1931)     1
Length: 9719, dtype: int64