#### Carnegie Mellon University - Tepper School of Business
#### 46-881 - Programming in R and Python
#### 22/23 - Mini 2 - Sections MO2 - Farahat

### FINAL EXAM 

**Due December 18th at 11:59 p.m. Pittsburgh time.**

---

Please provide your name and Andrew ID below:

- Name (Last, First):Hrishikesh Mysore Harishkumar

- Andrew ID: hmysoreh

---

### PROBLEM 1 (55 points)

The CDC Covid Tracker website includes a section on Health Equity Data ([link](https://covid.cdc.gov/covid-data-tracker/#health-equity-data)) with the following statement:

> Health equity is when everyone has the opportunity to be as healthy as possible. Achieving health equity requires valuing everyone equally with focused and ongoing efforts to address avoidable inequities, historical and contemporary injustices, and the elimination of disparities in health and healthcare. The population health impact of COVID-19 has exposed longstanding inequities that have systematically undermined the physical, social, economic, and emotional health of racial and ethnic minority populations and other population groups that are bearing a disproportionate burden of COVID-19.

In this problem, I ask you to use Python (pandas) to analyze data supplied by the CDC on Covid-19 vaccination rates along with variables measuring the degree of social vulnerability in US counties (see [this link](https://www.atsdr.cdc.gov/placeandhealth/svi/documentation/SVI_documentation_2018.html) for definitions). More information on the data and its context is available on the CDC website. 

The dataset, <vaccination_equity.csv>, is available on Canvas accompanying this problem. A data dictionary is provided in the table below. (Note: I've downloaded this dataset a little over a year ago, on October 14th 2021, so it's a bit out of date especially with respect to vaccination rates.)

| Column name |	Description |
| :-----------| :------------------|
| STATE	      | State abbreviation |
| COUNTY	  | County name        |
| FIPS	      | Unique county code |
| E_TOTPOP	  | Population estimate |
| EP_POV      |	Percentage of persons below poverty estimate|
| EP_UNEMP    |	Unemployment Rate estimate|
| EP_PCI      |	Per capita income estimate|
| EP_NOHSDP   |	Percentage of persons with no high school diploma (age 25+) estimate|
| EP_AGE65    |	Percentage of persons aged 65 and older estimate|
| EP_AGE17    |	Percentage of persons aged 17 and younger estimate|
| EP_DISABL   |	Percentage of civilian noninstitutionalized population with a disability estimate|
| EP_SNGPNT   |	Percentage of single parent households with children under 18 estimate|
| EP_MINRTY   |	Percentage minority (all persons except white, non-Hispanic) estimate|
| EP_LIMENG   |	Percentage of persons (age 5+) who speak English "less than well" estimate|
| EP_MUNIT    |	Percentage of housing in structures with 10 or more units estimate|
| EP_MOBILE   |	Percentage of mobile homes estimate|
| EP_CROWD    |	Percentage of occupied housing units with more people than rooms estimate|
| EP_NOVEH    |	Percentage of households with no vehicle available estimate|
| EP_GROUPQ   |	Percentage of persons in group quarters estimate|
| SVI         | County Social Vulnerability Index on a catgeorical scale|
| V_REPORT_COMPLETENESS | Percent of reporting completeness within county| 
| V_PCT_ALL   |	Percent of total population fully vaccinated|
| V_PCT_12YRS |	Percent of population 12 years and older fully vaccinated|
| V_PCT_18YRS |	Percent of population 18 years and older fully vaccinated|
| V_PCT_65YRS |	Percent of population 65 years and older fully vaccinated|

**Answer the following questions based on the data provided**.

#### Part (a)

How many counties are represented in this dataset?

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("vaccination_equity.csv")
df

,STATE,COUNTY,FIPS,E_TOTPOP,EP_POV,EP_UNEMP,EP_PCI,EP_NOHSDP,EP_AGE65,EP_AGE17,...,EP_MOBILE,EP_CROWD,EP_NOVEH,EP_GROUPQ,SVI,V_REPORT_COMPLETENESS,V_PCT_ALL,V_PCT_12YRS,V_PCT_18YRS,V_PCT_65YRS
0,AL,Autauga,1001,55200,15.4,4.2,29372,11.3,14.6,24.2,...,18.4,1.4,5.6,1.0,Low-Mod,92.5,34.7,40.8,42.5,62.2
1,AL,Blount,1009,57645,14.4,4.1,22656,19.8,17.8,23.4,...,25.2,1.6,4.2,0.9,Low-Mod,92.5,27.2,32.0,33.9,50.1
2,AL,Butler,1013,20025,23.5,6.7,20430,15.4,19.0,22.8,...,26.2,1.8,7.8,1.6,High,92.5,34.4,40.1,42.1,59.6
3,AL,Calhoun,1015,115098,18.6,8.8,24706,15.9,16.8,21.9,...,14.7,1.7,5.8,2.7,High,92.5,40.3,46.8,49.2,74.6
4,AL,Chambers,1017,33826,16.6,5.0,22827,18.6,18.9,20.7,...,14.0,3.0,7.3,1.5,Mod-High,92.5,27.3,31.7,33.2,48.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,TX,Duval,48131,11355,25.6,10.6,17864,32.9,17.8,26.1,...,13.0,7.4,10.0,4.4,High,NaN,NaN,NaN,NaN,NaN
3137,TX,Zapata,48505,14369,39.5,11.0,17228,40.0,13.9,33.6,...,34.2,18.1,7.9,0.2,High,NaN,NaN,NaN,NaN,NaN
3138,TX,Zavala,48507,12131,34.8,8.4,13350,38.0,13.7,29.5,...,22.8,5.6,14.4,1.6,High,NaN,NaN,NaN,NaN,NaN
3139,TX,Dimmit,48127,10663,29.8,16.4,18121,32.7,16.3,30.0,...,16.7,8.5,11.9,1.2,High,NaN,NaN,NaN,NaN,NaN
3140,TX,Jim Hogg,48247,5282,27.4,11.5,17798,25.8,17.6,31.4,...,8.6,7.7,11.5,0.5,High,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape

(3141, 25)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3141 entries, 0 to 3140
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   STATE                  3141 non-null   object
 1   COUNTY                 3141 non-null   object
 2   FIPS                   3141 non-null   int64
 3   E_TOTPOP               3141 non-null   int64
 4   EP_POV                 3141 non-null   float64
 5   EP_UNEMP               3141 non-null   float64
 6   EP_PCI                 3141 non-null   int64
 7   EP_NOHSDP              3141 non-null   float64
 8   EP_AGE65               3141 non-null   float64
 9   EP_AGE17               3141 non-null   float64
 10  EP_DISABL              3141 non-null   float64
 11  EP_SNGPNT              3141 non-null   float64
 12  EP_MINRTY              3141 non-null   float64
 13  EP_LIMENG              3141 non-null   float64
 14  EP_MUNIT               3141 non-null   float64
 15  EP_MOBILE              3141 non-null   float64
 16  EP_CROWD               3141 non-null   float64
 17  EP_NOVEH               3141 non-null   float64
 18  EP_GROUPQ              3141 non-null   float64
 19  SVI                    3057 non-null   object
 20  V_REPORT_COMPLETENESS  2790 non-null   float64
 21  V_PCT_ALL              2790 non-null   float64
 22  V_PCT_12YRS            2746 non-null   float64
 23  V_PCT_18YRS            2790 non-null   float64
 24  V_PCT_65YRS            2790 non-null   float64
dtypes: float64(19), int64(3), object(3)
memory usage: 613.6+ KB

In [5]:
len(df["COUNTY"])

3141

#### ANSWER: A total of 3141 counties are represented in the dataset.

#### Part (b)

What is the total population of the counties represented in the dataset?

In [6]:
sum(df["E_TOTPOP"])

322863723

#### ANSWER: The total population of the counties represented in 322863723

#### Part (c)

How many counties are missing a value in at least one of the columns?

In [7]:
df[df.isna().any(axis=1) == True]

,STATE,COUNTY,FIPS,E_TOTPOP,EP_POV,EP_UNEMP,EP_PCI,EP_NOHSDP,EP_AGE65,EP_AGE17,...,EP_MOBILE,EP_CROWD,EP_NOVEH,EP_GROUPQ,SVI,V_REPORT_COMPLETENESS,V_PCT_ALL,V_PCT_12YRS,V_PCT_18YRS,V_PCT_65YRS
27,AK,Valdez-Cordova,2261,9301,8.1,6.6,38507,4.0,12.4,23.6,...,11.3,2.3,7.1,2.7,NaN,NaN,NaN,NaN,NaN,NaN
50,CA,Inyo,6027,18085,10.2,5.2,31540,11.2,22.9,20.1,...,21.8,1.9,6.8,3.6,Mod-High,NaN,NaN,NaN,NaN,NaN
112,ID,Ada,16001,446052,11.0,3.8,33352,4.9,13.5,24.5,...,4.0,1.4,3.8,1.9,Low,97.6,51.0,NaN,66.3,91.0
113,ID,Bonner,16017,42711,14.7,3.7,27590,9.2,23.0,20.0,...,12.7,2.0,4.4,1.0,Low,97.6,36.3,NaN,45.1,66.8
114,ID,Boundary,16021,11549,16.8,3.9,25401,8.0,21.1,23.7,...,10.9,2.9,2.6,1.0,Low-Mod,97.6,28.9,NaN,37.5,59.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,TX,Duval,48131,11355,25.6,10.6,17864,32.9,17.8,26.1,...,13.0,7.4,10.0,4.4,High,NaN,NaN,NaN,NaN,NaN
3137,TX,Zapata,48505,14369,39.5,11.0,17228,40.0,13.9,33.6,...,34.2,18.1,7.9,0.2,High,NaN,NaN,NaN,NaN,NaN
3138,TX,Zavala,48507,12131,34.8,8.4,13350,38.0,13.7,29.5,...,22.8,5.6,14.4,1.6,High,NaN,NaN,NaN,NaN,NaN
3139,TX,Dimmit,48127,10663,29.8,16.4,18121,32.7,16.3,30.0,...,16.7,8.5,11.9,1.2,High,NaN,NaN,NaN,NaN,NaN
3140,TX,Jim Hogg,48247,5282,27.4,11.5,17798,25.8,17.6,31.4,...,8.6,7.7,11.5,0.5,High,NaN,NaN,NaN,NaN,NaN

In [8]:
len(df[df.isna().any(axis=1) == True])

395

#### ANSWER: There are 395 counties that are missing a value in at least one of the columns

**For the remaining parts of this problem, delete all the counties that have missing values in at least one column.** This will possibly bias the data, but ignore that for the purposes of this exam. Remove only rows with missing (NA) values; do not consider V_Report_Completeness < 100% as a missing value.

In [9]:
df_copy = df.dropna()

In [23]:
len(df_copy)

2746

In [24]:
df_copy

,STATE,COUNTY,FIPS,E_TOTPOP,EP_POV,EP_UNEMP,EP_PCI,EP_NOHSDP,EP_AGE65,EP_AGE17,...,EP_MOBILE,EP_CROWD,EP_NOVEH,EP_GROUPQ,SVI,V_REPORT_COMPLETENESS,V_PCT_ALL,V_PCT_12YRS,V_PCT_18YRS,V_PCT_65YRS
0,AL,Autauga,1001,55200,15.4,4.2,29372,11.3,14.6,24.2,...,18.4,1.4,5.6,1.0,Low-Mod,92.5,34.7,40.8,42.5,62.2
1,AL,Blount,1009,57645,14.4,4.1,22656,19.8,17.8,23.4,...,25.2,1.6,4.2,0.9,Low-Mod,92.5,27.2,32.0,33.9,50.1
2,AL,Butler,1013,20025,23.5,6.7,20430,15.4,19.0,22.8,...,26.2,1.8,7.8,1.6,High,92.5,34.4,40.1,42.1,59.6
3,AL,Calhoun,1015,115098,18.6,8.8,24706,15.9,16.8,21.9,...,14.7,1.7,5.8,2.7,High,92.5,40.3,46.8,49.2,74.6
4,AL,Chambers,1017,33826,16.6,5.0,22827,18.6,18.9,20.7,...,14.0,3.0,7.3,1.5,Mod-High,92.5,27.3,31.7,33.2,48.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3127,SD,Todd,46121,10146,55.1,13.2,10931,22.1,7.5,40.3,...,17.8,13.5,21.6,0.4,High,84.8,45.6,64.0,67.5,81.7
3128,SD,Ziebach,46137,2814,41.0,23.1,14943,15.9,9.0,32.0,...,27.2,14.2,12.2,0.0,High,84.8,24.6,29.0,30.2,48.5
3133,MS,Claiborne,28021,9120,44.0,15.6,13503,22.6,15.3,21.8,...,37.8,5.7,10.4,8.0,High,98.3,47.0,54.6,54.5,77.8
3134,SC,Allendale,45005,9214,26.8,16.4,14744,22.3,18.4,19.0,...,32.9,2.1,20.3,12.7,High,93.8,50.5,57.5,59.8,73.0
3135,SD,Oglala Lakota,46102,14335,49.3,19.7,10148,24.0,6.8,37.2,...,30.8,33.8,15.0,2.2,High,84.8,56.7,75.6,75.1,80.6

In [25]:
df_copy[df_copy.isna().any(axis=1) == True]

Empty DataFrame
Columns: [STATE, COUNTY, FIPS, E_TOTPOP, EP_POV, EP_UNEMP, EP_PCI, EP_NOHSDP, EP_AGE65, EP_AGE17, EP_DISABL, EP_SNGPNT, EP_MINRTY, EP_LIMENG, EP_MUNIT, EP_MOBILE, EP_CROWD, EP_NOVEH, EP_GROUPQ, SVI, V_REPORT_COMPLETENESS, V_PCT_ALL, V_PCT_12YRS, V_PCT_18YRS, V_PCT_65YRS]
Index: []

[0 rows x 25 columns]

#### Part (d)

Create a pivot table with a row for each State and a column for each Social Vulnerability Index category. Display in the table the population (summed across counties) of each State and SVI category combination.

In [26]:
df_copy.pivot_table(index = "STATE",  aggfunc="sum", values = ["E_TOTPOP","EP_POV","EP_UNEMP","EP_PCI","EP_NOHSDP","EP_AGE65","EP_AGE17","EP_DISABL","EP_SNGPNT","EP_MINRTY","EP_LIMENG","EP_MUNIT","EP_MOBILE","EP_CROWD","EP_NOVEH","EP_GROUPQ","SVI","V_REPORT_COMPLETENESS","V_PCT_ALL","V_PCT_12YRS","V_PCT_18YRS","V_PCT_65YRS"])

,EP_AGE17,EP_AGE65,EP_CROWD,EP_DISABL,EP_GROUPQ,EP_LIMENG,EP_MINRTY,EP_MOBILE,EP_MUNIT,EP_NOHSDP,...,EP_PCI,EP_POV,EP_SNGPNT,EP_UNEMP,E_TOTPOP,V_PCT_12YRS,V_PCT_18YRS,V_PCT_65YRS,V_PCT_ALL,V_REPORT_COMPLETENESS
STATE,,,,,,,,,,,,,,,,,,,,,
AK,234.2,111.3,137.4,128.2,62.6,18.1,587.9,46.2,35.7,111.1,...,255070,145.6,112.5,105.2,62842,586.1,592.4,682.8,483.8,869.4
AL,1480.5,1190.7,117.0,1272.7,175.5,54.7,2344.6,1430.1,214.1,1192.1,...,1545880,1362.6,602.4,538.5,4864680,2934.6,3076.4,4491.2,2519.1,6197.5
AR,1694.7,1426.5,197.4,1545.4,253.7,79.6,1847.1,1295.5,220.4,1213.7,...,1683205,1487.5,692.9,483.5,2990671,3465.0,3595.5,4850.2,2962.3,6765.0
AZ,347.2,301.1,80.1,239.0,54.0,70.2,743.2,324.2,69.5,239.2,...,351891,300.0,137.7,130.7,6946685,947.7,962.7,1156.7,811.9,1464.0
CA,1145.7,792.6,310.1,663.5,170.8,371.5,2452.0,339.5,446.3,824.2,...,1623539,760.5,455.1,366.5,39054386,3183.3,3256.9,3946.8,2721.7,4870.0
CO,1328.0,1169.5,158.3,881.2,238.4,151.0,1631.3,606.7,496.4,585.3,...,1964506,836.0,431.6,328.7,5531141,3614.6,3728.6,4708.2,3156.6,6233.6
CT,160.0,134.9,12.0,90.9,33.0,21.5,194.8,9.5,78.0,68.6,...,328170,73.3,64.6,48.1,3581504,610.9,620.8,736.6,537.0,787.2
DC,17.8,11.9,3.6,11.8,5.8,2.5,63.8,0.1,46.2,9.4,...,53321,16.8,8.4,7.4,684498,67.2,67.9,82.0,58.1,95.2
DE,64.0,57.1,5.4,39.6,7.3,5.8,104.7,30.7,26.2,33.7,...,97930,36.7,27.0,17.1,949495,189.7,194.6,251.3,163.8,288.6
FL,1311.5,1421.5,184.6,1116.7,415.0,206.7,2161.7,1487.5,576.6,980.6,...,1771375,1111.5,558.8,465.5,20598139,3635.4,3757.2,5284.6,3184.5,6612.9
GA,3626.8,2644.8,370.9,2537.9,654.6,257.2,5995.9,3531.5,488.0,2877.9,...,3723292,3285.7,1575.4,1114.9,10297484,3965.1,4058.6,5149.6,3398.1,9110.7
IA,2271.7,1920.0,146.2,1279.1,309.4,119.5,881.2,406.5,467.1,840.2,...,2912145,1098.6,755.7,365.0,3132499,5686.9,5983.1,8321.8,4846.3,9652.5
IL,2212.8,1895.5,159.4,1525.0,401.9,94.1,1336.3,797.6,454.5,1072.8,...,2886346,1386.1,847.1,604.6,12821497,5117.7,5339.6,7569.6,4415.3,9975.6
IN,2125.2,1556.3,162.6,1398.3,252.1,75.0,869.6,745.2,403.5,1106.9,...,2469904,1190.6,781.1,442.7,6637426,4739.7,4986.4,7387.8,4046.4,9080.4
KS,2497.1,2042.1,183.8,1611.0,321.6,175.9,1637.6,783.6,358.1,1092.6,...,2824029,1294.9,742.3,392.0,2908776,5247.3,5529.3,7636.0,4434.2,9828.0
KY,2710.0,2039.1,243.9,2470.8,360.7,59.5,994.5,2334.0,306.4,2225.8,...,2774155,2518.2,1010.4,847.6,4440204,6179.5,6459.4,8922.1,5277.0,11328.0
MA,272.0,246.9,22.0,169.1,53.8,45.8,308.0,15.0,152.1,119.8,...,563114,149.7,111.6,72.9,6830193,771.4,778.1,898.8,678.2,1254.4
MD,515.4,404.8,39.6,304.4,86.3,41.8,774.6,76.3,259.2,246.8,...,877000,248.6,212.4,131.3,6003435,1636.6,1677.9,2120.2,1410.6,2368.8
ME,300.2,338.0,23.4,280.1,41.2,6.4,93.3,148.8,59.4,133.8,...,463732,220.4,125.3,83.5,1332813,1158.5,1185.2,1432.0,1023.9,1544.0
MI,1666.1,1717.8,134.9,1384.3,264.2,50.9,1005.4,724.2,384.9,794.1,...,2231836,1243.9,646.6,552.6,9957488,4782.9,4976.3,6776.5,4188.6,8134.0
MN,2000.2,1648.5,155.1,1090.9,225.6,101.3,997.7,492.9,720.0,705.0,...,2681990,935.5,683.7,315.0,5527358,4993.5,5188.9,7225.7,4250.7,8178.0
MO,2608.7,2172.9,240.2,2041.3,398.3,65.6,1107.4,1373.3,352.3,1591.8,...,2758528,1912.9,942.7,606.2,6090062,4831.3,5091.1,7493.9,4129.5,10476.5
MS,1941.9,1329.6,236.2,1488.4,314.8,51.6,3762.4,1694.6,212.9,1606.4,...,1714371,1980.2,917.8,753.5,2988762,4100.0,4286.2,6233.3,3481.6,8060.6
MT,1216.2,1166.1,118.5,843.1,159.0,20.7,764.6,753.3,166.5,454.4,...,1571868,793.1,334.6,236.2,1041732,2675.6,2787.8,3971.8,2284.0,5353.6
NC,2103.4,1897.1,222.1,1687.3,319.6,172.4,3211.1,1992.4,366.0,1548.6,...,2541622,1751.8,874.5,700.6,10155624,5144.9,5348.7,7314.4,4467.6,9640.0
ND,1204.0,1072.2,97.0,666.0,149.7,22.3,676.6,491.3,369.8,508.4,...,1837616,562.4,335.0,137.5,752201,2437.4,2556.7,3608.9,2055.9,5040.3
NE,2143.9,1945.9,136.3,1274.5,241.8,132.1,999.6,631.7,324.2,796.0,...,2654770,1023.2,581.2,247.8,1904760,4017.5,4228.3,5769.8,3405.1,8332.8
NH,185.5,190.2,13.1,142.7,39.6,6.4,75.4,72.1,72.3,75.3,...,355402,91.7,72.5,40.8,1343622,663.5,677.5,854.1,589.2,941.0
NJ,459.3,339.0,55.2,233.3,49.8,107.0,794.7,29.1,271.4,216.8,...,844746,213.7,171.1,131.4,8881845,1445.0,1484.6,1668.5,1246.6,1963.5
NM,714.5,652.0,97.8,620.4,106.3,117.5,1840.0,762.0,99.8,509.4,...,759926,675.7,288.7,228.4,2053127,1709.8,1727.0,1914.8,1485.3,2697.6
NV,359.6,334.1,56.0,281.4,73.2,43.4,484.3,395.7,85.8,211.4,...,493581,207.4,140.6,110.9,2922849,775.4,809.2,1086.3,669.3,1613.3
NY,1261.1,1092.2,141.4,870.6,285.1,136.0,1169.6,460.4,566.7,683.2,...,1938478,843.2,531.3,357.0,19618453,4122.3,4214.4,5132.4,3591.7,6051.2
OH,1990.9,1528.1,121.7,1357.0,259.2,47.7,878.2,734.6,412.8,993.4,...,2420446,1241.6,767.2,483.0,11641879,4468.1,4689.9,6909.0,3832.0,8685.6
OK,1846.8,1355.0,204.4,1418.5,277.9,106.6,2273.0,1096.4,201.5,1084.4,...,1884251,1311.5,686.2,426.4,3918137,3507.6,3699.1,5409.6,2962.2,7222.6
OR,747.0,758.5,113.2,644.4,98.0,78.1,700.3,512.7,221.3,399.9,...,996844,549.1,271.1,245.6,4081943,2214.4,2285.3,2870.0,1921.4,3520.8
PA,1336.4,1294.9,83.1,1043.7,311.1,66.1,803.6,527.6,336.5,695.2,...,1935793,845.4,510.6,365.2,12791181,3861.4,4001.8,5419.4,3374.5,6324.8
RI,93.8,92.3,5.8,64.3,22.7,10.6,80.3,6.3,48.1,45.8,...,198454,49.8,36.8,26.4,1056611,384.1,387.9,467.0,340.4,467.0
SC,996.3,840.1,90.5,785.3,158.2,55.8,1981.6,1108.1,187.9,748.7,...,1106178,894.5,449.7,362.8,4955925,2290.8,2381.1,3353.0,1980.9,4314.8
SD,1650.9,1241.2,196.6,814.4,244.0,38.3,1320.5,764.0,317.3,673.2,...,1853116,1048.4,535.5,303.5,864289,3195.6,3336.1,4331.3,2643.5,5596.8
TN,2046.5,1756.2,186.0,1815.7,281.7,68.0,1297.8,1628.7,281.1,1609.0,...,2306908,1699.5,785.1,634.9,6651089,4280.4,4515.6,6835.0,3697.2,9300.5
UT,855.5,411.1,98.2,344.3,72.5,47.1,440.2,269.8,134.0,240.3,...,738566,344.2,186.0,116.4,3045350,1558.2,1653.4,2262.4,1277.4,2824.6
VA,2689.8,2468.5,207.1,2007.3,587.4,164.9,3798.0,1286.7,950.5,1837.1,...,4006733,1889.1,1079.3,745.6,8413774,6751.7,6985.7,9321.1,5873.7,11078.9
VT,266.2,272.4,23.1,212.0,45.2,5.0,83.9,112.2,55.7,115.0,...,447524,157.8,106.2,59.3,624977,781.6,790.9,967.2,689.9,1031.8
WA,845.0,766.7,132.6,645.2,88.9,131.3,940.7,473.5,270.7,438.7,...,1141875,555.4,303.9,236.9,7294336,2335.8,2408.0,3045.0,2009.4,3747.9
WI,1539.7,1377.6,122.5,958.1,180.0,55.7,788.4,448.7,407.7,604.8,...,2143602,829.3,563.0,283.8,5778394,4337.8,4499.8,6242.6,3753.8,6984.0
WV,1103.7,1105.0,69.8,1151.7,155.7,18.0,310.2,996.5,162.4,840.2,...,1301864,1013.6,395.6,409.9,1829054,1396.8,1442.6,2042.2,1219.1,3294.5
WY,533.0,395.4,48.9,309.5,65.5,19.4,309.4,342.7,97.3,167.4,...,723467,265.6,160.9,94.7,581836,1029.6,1083.5,1644.9,879.7,2217.2

#### Part (e)

Modify the pivot table created in Part (d) above so that the rows are scaled to sum to one for each State. Hint: For a pandas dataframe, say df, with numerical values (e.g. a pivot table), use df.div(df.sum(axis=1), axis=0) to scale the rows.

In [27]:
df_pivot = df_copy.pivot_table(index = "STATE",  aggfunc="sum", values = ["E_TOTPOP","EP_POV","EP_UNEMP","EP_PCI","EP_NOHSDP","EP_AGE65","EP_AGE17","EP_DISABL","EP_SNGPNT","EP_MINRTY","EP_LIMENG","EP_MUNIT","EP_MOBILE","EP_CROWD","EP_NOVEH","EP_GROUPQ","SVI","V_REPORT_COMPLETENESS","V_PCT_ALL","V_PCT_12YRS","V_PCT_18YRS","V_PCT_65YRS"])

In [28]:
df_pivot.div(df_pivot.sum(axis=1), axis=0)

,EP_AGE17,EP_AGE65,EP_CROWD,EP_DISABL,EP_GROUPQ,EP_LIMENG,EP_MINRTY,EP_MOBILE,EP_MUNIT,EP_NOHSDP,...,EP_PCI,EP_POV,EP_SNGPNT,EP_UNEMP,E_TOTPOP,V_PCT_12YRS,V_PCT_18YRS,V_PCT_65YRS,V_PCT_ALL,V_REPORT_COMPLETENESS
STATE,,,,,,,,,,,,,,,,,,,,,
AK,0.000725,0.000344,0.000425,0.000397,0.000194,0.000056,0.001819,1.429259e-04,0.000110,0.000344,...,0.789093,0.000450,0.000348,0.000325,0.194410,0.001813,0.001833,0.002112,0.001497,0.002690
AL,0.000230,0.000185,0.000018,0.000198,0.000027,0.000008,0.000364,2.219882e-04,0.000033,0.000185,...,0.239960,0.000212,0.000094,0.000084,0.755123,0.000456,0.000478,0.000697,0.000391,0.000962
AR,0.000360,0.000303,0.000042,0.000328,0.000054,0.000017,0.000392,2.751417e-04,0.000047,0.000258,...,0.357484,0.000316,0.000147,0.000103,0.635167,0.000736,0.000764,0.001030,0.000629,0.001437
AZ,0.000048,0.000041,0.000011,0.000033,0.000007,0.000010,0.000102,4.436812e-05,0.000010,0.000033,...,0.048158,0.000041,0.000019,0.000018,0.950683,0.000130,0.000132,0.000158,0.000111,0.000200
CA,0.000028,0.000019,0.000008,0.000016,0.000004,0.000009,0.000060,8.340433e-06,0.000011,0.000020,...,0.039885,0.000019,0.000011,0.000009,0.959442,0.000078,0.000080,0.000097,0.000067,0.000120
CO,0.000176,0.000155,0.000021,0.000117,0.000032,0.000020,0.000217,8.061139e-05,0.000066,0.000078,...,0.261021,0.000111,0.000057,0.000044,0.734915,0.000480,0.000495,0.000626,0.000419,0.000828
CT,0.000041,0.000034,0.000003,0.000023,0.000008,0.000005,0.000050,2.427176e-06,0.000020,0.000018,...,0.083845,0.000019,0.000017,0.000012,0.915046,0.000156,0.000159,0.000188,0.000137,0.000201
DC,0.000024,0.000016,0.000005,0.000016,0.000008,0.000003,0.000086,1.354224e-07,0.000063,0.000013,...,0.072209,0.000023,0.000011,0.000010,0.926964,0.000091,0.000092,0.000111,0.000079,0.000129
DE,0.000061,0.000054,0.000005,0.000038,0.000007,0.000006,0.000100,2.926637e-05,0.000025,0.000032,...,0.093357,0.000035,0.000026,0.000016,0.905156,0.000181,0.000186,0.000240,0.000156,0.000275
FL,0.000059,0.000063,0.000008,0.000050,0.000019,0.000009,0.000096,6.639327e-05,0.000026,0.000044,...,0.079064,0.000050,0.000025,0.000021,0.919380,0.000162,0.000168,0.000236,0.000142,0.000295
GA,0.000258,0.000188,0.000026,0.000180,0.000047,0.000018,0.000426,2.508777e-04,0.000035,0.000204,...,0.264503,0.000233,0.000112,0.000079,0.731533,0.000282,0.000288,0.000366,0.000241,0.000647
IA,0.000373,0.000315,0.000024,0.000210,0.000051,0.000020,0.000145,6.674298e-05,0.000077,0.000138,...,0.478143,0.000180,0.000124,0.000060,0.514323,0.000934,0.000982,0.001366,0.000796,0.001585
IL,0.000140,0.000120,0.000010,0.000097,0.000026,0.000006,0.000085,5.062940e-05,0.000029,0.000068,...,0.183217,0.000088,0.000054,0.000038,0.813873,0.000325,0.000339,0.000480,0.000280,0.000633
IN,0.000232,0.000170,0.000018,0.000153,0.000028,0.000008,0.000095,8.144978e-05,0.000044,0.000121,...,0.269959,0.000130,0.000085,0.000048,0.725465,0.000518,0.000545,0.000807,0.000442,0.000992
KS,0.000432,0.000353,0.000032,0.000279,0.000056,0.000030,0.000283,1.355926e-04,0.000062,0.000189,...,0.488665,0.000224,0.000128,0.000068,0.503329,0.000908,0.000957,0.001321,0.000767,0.001701
KY,0.000373,0.000280,0.000034,0.000340,0.000050,0.000008,0.000137,3.209778e-04,0.000042,0.000306,...,0.381509,0.000346,0.000139,0.000117,0.610629,0.000850,0.000888,0.001227,0.000726,0.001558
MA,0.000037,0.000033,0.000003,0.000023,0.000007,0.000006,0.000042,2.027145e-06,0.000021,0.000016,...,0.076101,0.000020,0.000015,0.000010,0.923053,0.000104,0.000105,0.000121,0.000092,0.000170
MD,0.000075,0.000059,0.000006,0.000044,0.000013,0.000006,0.000112,1.106893e-05,0.000038,0.000036,...,0.127227,0.000036,0.000031,0.000019,0.870925,0.000237,0.000243,0.000308,0.000205,0.000344
ME,0.000166,0.000187,0.000013,0.000155,0.000023,0.000004,0.000052,8.244421e-05,0.000033,0.000074,...,0.256936,0.000122,0.000069,0.000046,0.738459,0.000642,0.000657,0.000793,0.000567,0.000855
MI,0.000136,0.000140,0.000011,0.000113,0.000022,0.000004,0.000082,5.921848e-05,0.000031,0.000065,...,0.182499,0.000102,0.000053,0.000045,0.814233,0.000391,0.000407,0.000554,0.000343,0.000665
MN,0.000242,0.000200,0.000019,0.000132,0.000027,0.000012,0.000121,5.974734e-05,0.000087,0.000085,...,0.325100,0.000113,0.000083,0.000038,0.670004,0.000605,0.000629,0.000876,0.000515,0.000991
MO,0.000293,0.000244,0.000027,0.000229,0.000045,0.000007,0.000124,1.543600e-04,0.000040,0.000179,...,0.310061,0.000215,0.000106,0.000068,0.684528,0.000543,0.000572,0.000842,0.000464,0.001178
MS,0.000409,0.000280,0.000050,0.000314,0.000066,0.000011,0.000793,3.570433e-04,0.000045,0.000338,...,0.361209,0.000417,0.000193,0.000159,0.629716,0.000864,0.000903,0.001313,0.000734,0.001698
MT,0.000461,0.000442,0.000045,0.000320,0.000060,0.000008,0.000290,2.855625e-04,0.000063,0.000172,...,0.595867,0.000301,0.000127,0.000090,0.394902,0.001014,0.001057,0.001506,0.000866,0.002029
NC,0.000165,0.000149,0.000017,0.000132,0.000025,0.000014,0.000252,1.563078e-04,0.000029,0.000121,...,0.199395,0.000137,0.000069,0.000055,0.796729,0.000404,0.000420,0.000574,0.000350,0.000756
ND,0.000461,0.000410,0.000037,0.000255,0.000057,0.000009,0.000259,1.880918e-04,0.000142,0.000195,...,0.703522,0.000215,0.000128,0.000053,0.287977,0.000933,0.000979,0.001382,0.000787,0.001930
NE,0.000466,0.000423,0.000030,0.000277,0.000053,0.000029,0.000217,1.374418e-04,0.000071,0.000173,...,0.577610,0.000223,0.000126,0.000054,0.414427,0.000874,0.000920,0.001255,0.000741,0.001813
NH,0.000109,0.000112,0.000008,0.000084,0.000023,0.000004,0.000044,4.231512e-05,0.000042,0.000044,...,0.208584,0.000054,0.000043,0.000024,0.788565,0.000389,0.000398,0.000501,0.000346,0.000552
NJ,0.000047,0.000035,0.000006,0.000024,0.000005,0.000011,0.000082,2.988392e-06,0.000028,0.000022,...,0.086750,0.000022,0.000018,0.000013,0.912111,0.000148,0.000152,0.000171,0.000128,0.000202
NM,0.000253,0.000230,0.000035,0.000219,0.000038,0.000042,0.000650,2.693059e-04,0.000035,0.000180,...,0.268573,0.000239,0.000102,0.000081,0.725616,0.000604,0.000610,0.000677,0.000525,0.000953
NV,0.000105,0.000098,0.000016,0.000082,0.000021,0.000013,0.000141,1.155579e-04,0.000025,0.000062,...,0.144143,0.000061,0.000041,0.000032,0.853572,0.000226,0.000236,0.000317,0.000195,0.000471
NY,0.000058,0.000051,0.000007,0.000040,0.000013,0.000006,0.000054,2.132548e-05,0.000026,0.000032,...,0.089789,0.000039,0.000025,0.000017,0.908716,0.000191,0.000195,0.000238,0.000166,0.000280
OH,0.000141,0.000108,0.000009,0.000096,0.000018,0.000003,0.000062,5.209063e-05,0.000029,0.000070,...,0.171634,0.000088,0.000054,0.000034,0.825528,0.000317,0.000333,0.000490,0.000272,0.000616
OK,0.000316,0.000232,0.000035,0.000243,0.000048,0.000018,0.000389,1.878079e-04,0.000035,0.000186,...,0.322763,0.000225,0.000118,0.000073,0.671158,0.000601,0.000634,0.000927,0.000507,0.001237
OR,0.000147,0.000149,0.000022,0.000126,0.000019,0.000015,0.000137,1.005854e-04,0.000043,0.000078,...,0.195569,0.000108,0.000053,0.000048,0.800827,0.000434,0.000448,0.000563,0.000377,0.000691
PA,0.000091,0.000088,0.000006,0.000071,0.000021,0.000004,0.000054,3.574836e-05,0.000023,0.000047,...,0.131163,0.000057,0.000035,0.000025,0.866686,0.000262,0.000271,0.000367,0.000229,0.000429
RI,0.000075,0.000073,0.000005,0.000051,0.000018,0.000008,0.000064,5.009021e-06,0.000038,0.000036,...,0.157787,0.000040,0.000029,0.000021,0.840093,0.000305,0.000308,0.000371,0.000271,0.000371
SC,0.000164,0.000138,0.000015,0.000129,0.000026,0.000009,0.000326,1.820901e-04,0.000031,0.000123,...,0.181774,0.000147,0.000074,0.000060,0.814389,0.000376,0.000391,0.000551,0.000326,0.000709
SD,0.000601,0.000452,0.000072,0.000297,0.000089,0.000014,0.000481,2.782246e-04,0.000116,0.000245,...,0.674846,0.000382,0.000195,0.000111,0.314747,0.001164,0.001215,0.001577,0.000963,0.002038
TN,0.000227,0.000195,0.000021,0.000202,0.000031,0.000008,0.000144,1.809414e-04,0.000031,0.000179,...,0.256287,0.000189,0.000087,0.000071,0.738907,0.000476,0.000502,0.000759,0.000411,0.001033
UT,0.000225,0.000108,0.000026,0.000091,0.000019,0.000012,0.000116,7.105336e-05,0.000035,0.000063,...,0.194506,0.000091,0.000049,0.000031,0.802010,0.000410,0.000435,0.000596,0.000336,0.000744
VA,0.000216,0.000198,0.000017,0.000161,0.000047,0.000013,0.000304,1.030918e-04,0.000076,0.000147,...,0.321024,0.000151,0.000086,0.000060,0.674121,0.000541,0.000560,0.000747,0.000471,0.000888
VT,0.000247,0.000253,0.000021,0.000197,0.000042,0.000005,0.000078,1.040467e-04,0.000052,0.000107,...,0.415004,0.000146,0.000098,0.000055,0.579561,0.000725,0.000733,0.000897,0.000640,0.000957
WA,0.000100,0.000091,0.000016,0.000076,0.000011,0.000016,0.000111,5.599713e-05,0.000032,0.000052,...,0.135041,0.000066,0.000036,0.000028,0.862644,0.000276,0.000285,0.000360,0.000238,0.000443
WI,0.000194,0.000173,0.000015,0.000120,0.000023,0.000007,0.000099,5.639509e-05,0.000051,0.000076,...,0.269420,0.000104,0.000071,0.000036,0.726260,0.000545,0.000566,0.000785,0.000472,0.000878
WV,0.000351,0.000351,0.000022,0.000366,0.000049,0.000006,0.000099,3.164993e-04,0.000052,0.000267,...,0.413486,0.000322,0.000126,0.000130,0.580928,0.000444,0.000458,0.000649,0.000387,0.001046
WY,0.000405,0.000301,0.000037,0.000235,0.000050,0.000015,0.000235,2.605986e-04,0.000074,0.000127,...,0.550144,0.000202,0.000122,0.000072,0.442444,0.000783,0.000824,0.001251,0.000669,0.001686

#### Part (f)

What is the total number of persons fully vaccinated in the counties represented in the dataset?

In [29]:
sum(df_copy["E_TOTPOP"] * (df_copy["V_PCT_ALL"]/100))

153178737.36499995

#### ANSWER: The total number of persons fully vaccinated in the counties is equal to 153178737.4

#### Part (g)

Without adjusting for population, what is the median, across all counties, of V_PCT_12YRS (Percent of population 12 years and older fully vaccinated)?

In [30]:
df_copy["V_PCT_12YRS"].median()

50.2

#### ANSWER: The median, across all counties, of V_PCT_12YRS is 50.2

#### Part (h)

Create a table showing the median of V_PCT_12YRS grouped by the Social Vulnerability Index, SVI.

In [31]:
df_copy.pivot_table(index = "SVI", aggfunc = "median", values = ["V_PCT_12YRS"])

          V_PCT_12YRS
SVI
High            46.50
Low             53.90
Low-Mod         51.25
Mod-High        48.20

#### Part (i)
What is the coefficient of correlation between V_PCT_12YRS and EP_POV? Hint: Use the corr() method; see help(pd.DataFrame.corr).

In [32]:
print(df_copy["EP_POV"].corr(df_copy["V_PCT_12YRS"]))

-0.2522880086714833

#### ANSWER: The coefficient of correlation between V_PCT_12YRS and EP_POV is -0.2523

**The remaining parts focus on the state of Pennsylvania**.

#### Part (j)

Without adjusting for population, what is the median of V_PCT_12YRS across all counties in Pennsylvania?

In [33]:
df_copy["STATE"].unique()

array(['AL', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'IL', 'IN',
       'IA', 'KS', 'KY', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT',
       'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR',
       'PA', 'RI', 'SC', 'SD', 'TN', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI',
       'WY', 'AK', 'DC'], dtype=object)

In [34]:
df_copy[df_copy["STATE"] == 'PA'].pivot_table(index = "STATE", values ="V_PCT_12YRS", aggfunc = "median")

       V_PCT_12YRS
STATE
PA            59.2

#### ANSWER: From the above table, the median of V_PCT_12YRS across all counties in Pennsylvania is 59.2

#### Part (k)

Which 5 counties in PA has the highest V_PCT_12YRS? Which 5 counties had the lowest?

In [35]:
df_pa_order = df_copy[df_copy["STATE"] == 'PA'].sort_values(by=["V_PCT_12YRS"], ascending=False)

In [36]:
df_pa_order.head(5)

,STATE,COUNTY,FIPS,E_TOTPOP,EP_POV,EP_UNEMP,EP_PCI,EP_NOHSDP,EP_AGE65,EP_AGE17,...,EP_MOBILE,EP_CROWD,EP_NOVEH,EP_GROUPQ,SVI,V_REPORT_COMPLETENESS,V_PCT_ALL,V_PCT_12YRS,V_PCT_18YRS,V_PCT_65YRS
1928,PA,Montour,42093,18294,11.1,2.2,34095,9.3,20.4,20.1,...,7.2,1.7,11.8,4.1,Low-Mod,94.4,70.4,81.6,83.9,98.7
971,PA,Lehigh,42077,362613,12.5,6.5,32252,11.4,16.2,22.8,...,2.1,2.0,8.9,2.5,Mod-High,94.4,64.7,75.7,78.2,99.9
1923,PA,Lackawanna,42069,211454,15.1,4.8,28427,9.1,19.3,20.3,...,2.6,1.5,10.1,3.8,Mod-High,94.4,65.5,75.5,77.3,94.7
2355,PA,Delaware,42045,563527,10.0,6.0,38251,7.2,15.7,22.2,...,0.3,1.5,10.6,3.9,Low-Mod,94.4,64.3,75.1,75.9,93.4
952,PA,Bucks,42017,626370,6.1,4.5,44103,6.1,17.6,20.8,...,1.9,1.1,4.8,1.5,Low,94.4,63.7,72.8,73.7,86.6

In [37]:
df_pa_order.tail(5)

,STATE,COUNTY,FIPS,E_TOTPOP,EP_POV,EP_UNEMP,EP_PCI,EP_NOHSDP,EP_AGE65,EP_AGE17,...,EP_MOBILE,EP_CROWD,EP_NOVEH,EP_GROUPQ,SVI,V_REPORT_COMPLETENESS,V_PCT_ALL,V_PCT_12YRS,V_PCT_18YRS,V_PCT_65YRS
951,PA,Bradford,42015,61304,12.0,4.8,27319,11.1,20.3,22.1,...,15.1,1.7,7.4,1.3,Low-Mod,94.4,37.5,43.7,45.9,63.6
973,PA,McKean,42083,41806,16.8,6.8,25517,8.9,18.5,20.0,...,8.7,0.9,9.4,7.2,Mod-High,94.4,34.8,39.8,41.9,57.7
949,PA,Bedford,42009,48611,12.7,4.9,25163,12.5,21.8,20.0,...,14.6,1.7,5.7,1.0,Low-Mod,94.4,34.0,38.7,41.1,63.7
965,PA,Fulton,42057,14506,11.4,5.6,26082,12.7,20.6,20.3,...,18.1,0.9,6.5,0.2,Low,94.4,29.9,34.3,36.5,59.4
979,PA,Potter,42105,16937,14.3,6.6,24087,11.9,22.8,21.0,...,13.9,0.8,7.2,1.6,Low-Mod,94.4,29.7,34.0,35.9,52.4

#### Answer:

#### 5 counties in PA with the highest V_PCT_12YRS: 
- Montour
- Lehigh
- Lackawanna
- Delaware
- Bucks

#### 5 counties in PA with the lowest V_PCT_12YRS: 
- Bradford
- McKean
- Bedford
- Fulton
- Potter

### PROBLEM 2 (45 points)

In this problem I ask you to implement in Python a simulation model of a simpified airline revenue management problem.

Consider an airline operating a flight with an aircraft whose capacity is 189 passenger seats. All seats on this aircraft are identical (that is, there is no business or first-class compartments). The marginal cost of each additional passenger is negligible. 

There are two fares for this flights: Standard and Premium. Standard tickets cost 249 dollars and have advance-purchase and other restrictions. Premium tickets cost 349 dollars and have far fewer restrictions.

Because of the advance-purchase restriction of the Standard tickets and the flexibility of the Premium tickets we will assume that **all** of the demand for Standard tickets materializes before any of the demand for Premium tickets. In other words, Standard fare passengers book early and Premium fare passengers book later.

It is estimated that the demand for Standard tickets follows approximately a Normal distribution with mean equal to 150 and a standard deviation equal to 30. The demand for Premium tickets is estimated to also follow approximately a Normal distribution but with mean equal to 100 and a standard deviation equal to 40. Assume the demands to be uncorrelated. (Do not worry about fractionality or the possibility of negative demand values).

For each part of this problem use 10,000 trials per simulation and a value of 123 for the random seed.

#### Part (a) 

Suppose the airline accepts all bookings, subject to capacity, on a first-come first-serve basis. Run a simulation to compute the expected (or average) revenue per flight?

### Approach: 

* In part (a), as there is no limit set on the number of standard tickets that can be purchased, we will use the random number generator normal function to determine the demand for the standard fare. The cap of 189 is applied to make sure airline accepts all bookings, subject to aircraft capacity. Using the determined standard fare demand, we calculate the 'standard revenue'.

* Next, as we assume that all of the demand for Standard tickets materializes before any of the demand for Premium tickets, based on the remaining number of seats in the aircraft after allocating standard fare seats, we run the simulation for the premium demand until the aircraft capacity is reached and calculate the corresponding 'premium revenue'.

* Total revenue is a summation of 'standard revenue' and 'premium revenue'.

* After simulating the above for 10000 trials, we take the average to determine the average revenue per flight.

In [1]:
# Importing required libraries/packages
import numpy as np

In [2]:
# Defining required variables

aircraft_capacity = 189
standard_ticket_price = 249
premium_ticket_price = 349
std_ticket_mean = 150
std_ticket_stdev = 30
premium_ticket_mean = 100
premium_ticket_stdev = 40
trials = 10000

In [3]:
tot_revenue =[]
rng = np.random.default_rng(seed=123)
for i in range(trials):
    
    standard_ticket_demand = rng.normal(loc= std_ticket_mean, scale = std_ticket_stdev)
    if standard_ticket_demand >= aircraft_capacity:
        total_seats_filled = aircraft_capacity
    else:
        total_seats_filled = int(standard_ticket_demand)
       
    revenue_standard = total_seats_filled * standard_ticket_price
       
    revenue_premium = 0
    if total_seats_filled < aircraft_capacity:
        premium_ticket_demand = rng.normal(loc = premium_ticket_mean, scale = premium_ticket_stdev)
        for demand in range(int(premium_ticket_demand)):
            revenue_premium += premium_ticket_price
            total_seats_filled += 1
            if total_seats_filled == aircraft_capacity:
                break
        total_revenue = revenue_standard + revenue_premium
        tot_revenue.append(total_revenue)
    else:
        total_revenue = revenue_standard + revenue_premium
        tot_revenue.append(total_revenue)

avg_tot_revenue = np.mean(tot_revenue)
print("The average revenue per flight is:", avg_tot_revenue)

The average revenue per flight is: 50176.0616

#### Part (b) 

Accepting customers on a first-come first-serve effectively dilutes revenue. Passengers requesting Standard tickets books early and this limits (due to aircraft capacity) the airline's ability to issue higher-fare Premium tickets for passegers booking later. Therefore, the airline's revenue management system will implement a **booking limit** on Standard tickets. That is, it will set a limit on the maximum number of Standard tickets that will be issued on any given flight (even before it knows precisely the demand for Premium tickets). Requests for Standard ticket bookings declined due to the booking limit is lost demand.  

Run a simulation to compute the expected (or average) revenue per flight if the airline chooses to set a booking limit of 110 seats.

### Approach:

* The approach is similar to part(a) except for the fact that the booking limit of 110 is set on the max number of tickets that can be purchased using the standard fare per flight.

In [4]:
booking_limit = 110

In [5]:
tot_revenue =[]
rng = np.random.default_rng(seed=123)
for i in range(trials):
    
    standard_ticket_demand = rng.normal(loc= std_ticket_mean, scale = std_ticket_stdev)
    if standard_ticket_demand >= booking_limit:
        total_seats_filled = booking_limit
    else:
        total_seats_filled = int(standard_ticket_demand)
       
    revenue_standard = total_seats_filled * standard_ticket_price 
    
    revenue_premium = 0
    premium_ticket_demand = rng.normal(loc = premium_ticket_mean, scale = premium_ticket_stdev)
    for demand in range(int(premium_ticket_demand)):
        revenue_premium += premium_ticket_price
        total_seats_filled += 1
        if total_seats_filled == aircraft_capacity:
            break
    total_revenue = revenue_standard + revenue_premium
    tot_revenue.append(total_revenue)

    
avg_tot_revenue = np.mean(tot_revenue)
print("The average revenue per flight is:", avg_tot_revenue)

The average revenue per flight is: 52254.0921

### Conclusion:

* As expected by the airline's revenue management system, the average revenue per flight is going to be definitely higher if there is a booking limit set of the standard fare seats.

---
### END