In [1]:
#!pip install yfinance

In [2]:
from pandas_datareader.data import DataReader
from datetime import date, datetime, timedelta
import pandas as pd

# **Exercise 1**
* Import BP Stock data from Jan 1, 2004 to December 31, 2019.  
    * How many trading days are in this sample?
        * You can use the df.shape function
* What is the close price of Exxon stock on December 25, 2019? <br>

# **Exercise 1 cont'd.**
* Save this BP price data to a folder called data.

    * Ensure that it is saved, by opening the CSV file using Excel.
    * Compare the open price of Exxon stock on January 3, 2004 in the CSV file with your notebook?

# **Exercise 1 cont'd.**
* Compute daily returns for the BP data.
    * Returns can be computed from prices: 
    * returns = prices.pct_change()
    * For example, returns = df['Adj Close].pct_change()
<br>

* Compute the minimum daily return:
    * df.min(axis='rows')
<br>

* For each day, compute which the maximum change in the variables:
    * df.max(axis='column')

In [3]:
ticker = 'ibm'
source = 'yahoo'
end_date = date(2019,12,31)
begin_date = date(2004,1,1)

#df_BP = DataReader(ticker, 'yahoo',  begin_date, end_date)
from pandas_datareader import data as DataReader
import yfinance as yf
yf.pdr_override()
df_BP = DataReader.get_data_yahoo(ticker, start=begin_date, end=end_date)

#df_BP.to_csv('data/df_BP.csv') 
#df_BP = pd.read_csv('data/df_BP.csv', parse_dates=['Date'], index_col='Date')

print(df_BP.shape)
print(df_BP.tail())

[*********************100%***********************]  1 of 1 completed
(4026, 6)
                  Open        High         Low       Close   Adj Close  \
Date
2019-12-23  129.808792  130.162521  129.063095  129.588913  115.837708
2019-12-24  129.646271  129.655838  128.690247  129.043976  115.350601
2019-12-26  129.043976  129.359467  128.728485  128.977051  115.290779
2019-12-27  129.063095  129.780121  128.938812  129.321228  115.598434
2019-12-30  129.254303  129.349899  126.673042  126.969406  113.496162

             Volume
Date
2019-12-23  2932147
2019-12-24  1257397
2019-12-26  2227666
2019-12-27  2878801
2019-12-30  4308369

In [4]:
import yfinance as yf
begin_date = '2014-01-01'
end_date = '2022-01-01'
symbol = 'BP'
df_BP1 = yf.download("BP", start="2004-01-01", end="2019-12-31", )
#df_BP1 = yf.download("BP SPY", start="2019-12-31", end="2004-01-01")
df_BP1

[*********************100%***********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close   Volume
Date
2004-01-02  49.529999  49.599998  49.200001  49.400002  19.812305  2972500
2004-01-05  49.349998  50.049999  49.310001  49.900002  20.012838  4142800
2004-01-06  50.090000  50.400002  49.959999  50.220001  20.141172  3172900
2004-01-07  49.130001  49.150002  48.750000  49.020000  19.659904  5830200
2004-01-08  49.200001  49.340000  48.930000  49.070000  19.679960  2941100
...               ...        ...        ...        ...        ...      ...
2019-12-23  37.709999  38.119999  37.709999  38.110001  33.257023  6378500
2019-12-24  37.970001  38.139999  37.959999  38.040001  33.195934  2348400
2019-12-26  38.060001  38.200001  37.939999  37.980000  33.143570  4504200
2019-12-27  38.240002  38.250000  37.860001  37.860001  33.038853  5436600
2019-12-30  37.799999  37.970001  37.570000  37.599998  32.811958  6105900

[4026 rows x 6 columns]

In [5]:
returns = df_BP.pct_change()
returns.head()

                Open      High       Low     Close  Adj Close    Volume
Date
2004-01-02       NaN       NaN       NaN       NaN        NaN       NaN
2004-01-05 -0.009261  0.000430  0.008772  0.016384   0.016385 -0.009666
2004-01-06  0.002174  0.001074  0.001522  0.000108   0.000107 -0.169873
2004-01-07  0.010195  0.002039  0.003582 -0.003009  -0.003009  0.125023
2004-01-08  0.000752 -0.001820 -0.004758  0.002802   0.002803  0.254120

In [6]:
print(returns.min(axis='rows'))
print(returns.max(axis='columns'))

Open        -0.098424
High        -0.071654
Low         -0.087727
Close       -0.082975
Adj Close   -0.082975
Volume      -0.868648
dtype: float64
Date
2004-01-02         NaN
2004-01-05    0.016385
2004-01-06    0.002174
2004-01-07    0.125023
2004-01-08    0.254120
                ...
2019-12-23    0.000371
2019-12-24   -0.001252
2019-12-26    0.771649
2019-12-27    0.292295
2019-12-30    0.496585
Length: 4026, dtype: float64